### PR TITLE
Create Euploid_Adults

### PR DESCRIPTION
**Pull request by LME9517**

### CODE REVIEW

**Review by psolymos — CHANGES_REQUESTED** [review]
Thank you for your PR. Please make the following changes before merge:

- move the file inside the /inst/extdata/euploid/ folder
- add .xyz extension
- add a README.md file describing the nature of the data set (check other directories in the /inst/extdata folder for examples. 

Thanks.

**Comment by LME9517** [comment]
Hi Peter, hopefully everything is going well.

I have done the changes that you asked, could you check them and give me your opinion if they are well written. I would like to test the data in R with this data.

Thanks,

Luis Miguel Echeverry.

________________________________
De: Peter Solymos <notifications@github.com>
Enviado: viernes, 30 de octubre de 2020 9:44 a. m.
Para: psolymos/EDMAinR <EDMAinR@noreply.github.com>
Cc: LME9517 <luis-mi-e-q@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [psolymos/EDMAinR] Create Euploid_Adults (#7)


@psolymos requested changes on this pull request.

Thank you for your PR. Please make the following changes before merge:

  *   move the file inside the /inst/extdata/euploid/ folder
  *   add .xyz extension
  *   add a README.md file describing the nature of the data set (check other directories in the /inst/extdata folder for examples.

Thanks.

**Comment by psolymos** [comment]
Hi Luis, thanks. Are you trying to read in the data for analysis?

You can just use `read_xyz("Euploid_Adults")` to read in your data for analysis? It doesn't have to be part of the package. The system file thing in the examples is just the way I ship text files with the package as examples, but you can read files from anywhere in your file system. Either set working directory (`setwd()`) or use the path as part of the file argument.

**Comment by LME9517** [comment]
Hi Peter,

Yes, i have been trying to read the data in the package "EDMAinR". However, i have tryied different ways to read it without success. I used the following script "file1 <- system.file("inst/extdata/EDMA_EU_DS/Euploid_Adults.xyz", package="EDMAinR"), but it did not work. Got the error message: "Error in character(nchar(h[2L])) : vector size can not be NA". Could you give me a hand? The two files that contain the data are attached in this mail.

Thank you very much for your help!!!

________________________________
De: Peter Solymos <notifications@github.com>
Enviado: sábado, 31 de octubre de 2020 3:17 p. m.
Para: psolymos/EDMAinR <EDMAinR@noreply.github.com>
Cc: LME9517 <luis-mi-e-q@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [psolymos/EDMAinR] Create Euploid_Adults (#7)


Hi Luis, thanks. Are you trying to read in the data for analysis?

You can just use read_xyz("Euploid_Adults") to read in your data for analysis? It doesn't have to be part of the package. The system file thing in the examples is just the way I ship text files with the package as examples, but you can read files from anywhere in your file system. Either set working directory (setwd()) or use the path as part of the file argument.

**Comment by psolymos** [comment]
Sorry for the confusion. The system.file() piece is not needed, you only need to know where your file is located. E.g. if your file (assuming windows) is at 'c:/Users/User/Documents/Euploid_Adults.xyz' then you just need to do:

```
x <- read_xyz("c:/Users/User/Documents/Euploid_Adults.xyz")
```

The system.file is used to locate the text files that are distributed with the package itself (so that you don't have to download it first). Your file already exists and the `read_xyz` command should be able to read it.

**Pull request closed without merging**
